apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    descriptionShort: |
      The Crossplane Kubernetes provider enables management of Kubernetes Objects.
spec:
  controller:
    image: rossplane/provider-kubernetes-controller:VERSION:v0.3.0
    permissionRequests:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'